import pandas as pd

def get_initial_assets_df() -> pd.DataFrame:
    """Returns 20 comprehensive enterprise assets with monetary value in INR."""
    return pd.DataFrame([
        {"asset_id": "AST-101", "asset_name": "Core Banking Transaction DB", "asset_type": "Database", "asset_value": 45000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "No (Internal VPC)", "data_sensitivity": "PCI / Highly Confidential", "number_of_users": 250000, "location": "AWS ap-south-1 (Mumbai)", "system_availability": "99.999%", "owner": "DBA & Core Platform Team", "status": "Active"},
        {"asset_id": "AST-102", "asset_name": "Public NetBanking & API Gateway", "asset_type": "Web Application", "asset_value": 28000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "Yes (Public Edge)", "data_sensitivity": "PII & Auth Tokens", "number_of_users": 850000, "location": "Cloudflare / AWS Mumbai", "system_availability": "99.99%", "owner": "Digital Banking Engineering", "status": "Active"},
        {"asset_id": "AST-103", "asset_name": "Active Directory & IAM Domain Controller", "asset_type": "Server", "asset_value": 32000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "No (Corporate LAN)", "data_sensitivity": "Admin Credentials / Hashes", "number_of_users": 4500, "location": "On-Premises Data Center (Hyd)", "system_availability": "99.999%", "owner": "Enterprise Infrastructure", "status": "Active"},
        {"asset_id": "AST-104", "asset_name": "Customer Support CRM Portal (SaaS)", "asset_type": "Cloud Resource", "asset_value": 9500000, "criticality": 3, "business_importance": "Moderate", "internet_exposure": "Yes (SaaS Public)", "data_sensitivity": "Customer PII", "number_of_users": 650, "location": "Salesforce US-West", "system_availability": "99.9%", "owner": "Customer Ops Team", "status": "Active"},
        {"asset_id": "AST-105", "asset_name": "UPI & Payment Switch Engine", "asset_type": "Server", "asset_value": 60000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "Yes (Restricted mTLS)", "data_sensitivity": "Cardholder Data (CHD)", "number_of_users": 120000, "location": "NPCI Leased Line / AWS", "system_availability": "99.999%", "owner": "Payments Team", "status": "Active"},
        {"asset_id": "AST-106", "asset_name": "Employee Laptops & Workstations Fleet", "asset_type": "Endpoint", "asset_value": 12000000, "criticality": 3, "business_importance": "Operational", "internet_exposure": "Yes (Remote Work)", "data_sensitivity": "Internal Proprietary", "number_of_users": 4500, "location": "Distributed Pan-India", "system_availability": "99.5%", "owner": "IT Service Desk", "status": "Active"},
        {"asset_id": "AST-107", "asset_name": "Data Lake & AI Analytics Cluster", "asset_type": "Cloud Resource", "asset_value": 21000000, "criticality": 4, "business_importance": "High", "internet_exposure": "No (Private Subnet)", "data_sensitivity": "Aggregated Analytics", "number_of_users": 350, "location": "GCP asia-south1", "system_availability": "99.9%", "owner": "Data Science & BI", "status": "Active"},
        {"asset_id": "AST-108", "asset_name": "ATM Network Switch & HSM", "asset_type": "Network Device", "asset_value": 38000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "No (Air-gapped Zone)", "data_sensitivity": "PIN Blocks / Key Store", "number_of_users": 200, "location": "Data Center Mumbai", "system_availability": "99.999%", "owner": "ATM Switching Ops", "status": "Active"},
        {"asset_id": "AST-109", "asset_name": "Corporate Email Exchange & O365 Gateway", "asset_type": "Cloud Resource", "asset_value": 15000000, "criticality": 4, "business_importance": "High", "internet_exposure": "Yes (Cloud O365)", "data_sensitivity": "Executive Email Comms", "number_of_users": 4500, "location": "Microsoft Azure India", "system_availability": "99.95%", "owner": "Corporate IT", "status": "Active"},
        {"asset_id": "AST-110", "asset_name": "Enterprise Next-Gen Perimeter Firewall", "asset_type": "Network Device", "asset_value": 18000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "Yes (Edge Router)", "data_sensitivity": "Network Flow Metadata", "number_of_users": 10000, "location": "HQ Data Center Mumbai", "system_availability": "99.999%", "owner": "Network Security Ops", "status": "Active"},
        {"asset_id": "AST-111", "asset_name": "SWIFT Financial Messaging Node", "asset_type": "Server", "asset_value": 55000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "No (Dedicated Lease)", "data_sensitivity": "Interbank Wire Messages", "number_of_users": 50, "location": "Secure Vault DC", "system_availability": "99.999%", "owner": "Treasury & Remittance", "status": "Active"},
        {"asset_id": "AST-112", "asset_name": "CI/CD Deployment & Source Code Repo", "asset_type": "Server", "asset_value": 24000000, "criticality": 4, "business_importance": "High", "internet_exposure": "No (VPN Restricted)", "data_sensitivity": "Proprietary Code & Keys", "number_of_users": 280, "location": "GitLab Self-Hosted AWS", "system_availability": "99.9%", "owner": "DevSecOps Engineering", "status": "Active"},
        {"asset_id": "AST-113", "asset_name": "HR & Payroll Processing System", "asset_type": "Web Application", "asset_value": 8500000, "criticality": 3, "business_importance": "Operational", "internet_exposure": "No (Corporate LAN)", "data_sensitivity": "Salary / Bank Details", "number_of_users": 4500, "location": "On-Prem DC", "system_availability": "99.5%", "owner": "Human Resources", "status": "Active"},
        {"asset_id": "AST-114", "asset_name": "Loan Origination & Credit Scoring Portal", "asset_type": "Web Application", "asset_value": 19000000, "criticality": 4, "business_importance": "High", "internet_exposure": "Yes (Partner API)", "data_sensitivity": "CIBIL / Financial Records", "number_of_users": 2000, "location": "AWS ap-south-1", "system_availability": "99.9%", "owner": "Retail Lending", "status": "Active"},
        {"asset_id": "AST-115", "asset_name": "Customer KYC & Aadhaar Vault Storage", "asset_type": "Database", "asset_value": 48000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "No (Encrypted Enclave)", "data_sensitivity": "UIDAI Aadhaar / Biometrics", "number_of_users": 5000000, "location": "UIDAI Compliant DC", "system_availability": "99.999%", "owner": "Compliance & Security", "status": "Active"},
        {"asset_id": "AST-116", "asset_name": "Enterprise SIEM & SOC Log Collector", "asset_type": "Server", "asset_value": 16000000, "criticality": 4, "business_importance": "High", "internet_exposure": "No (Internal Private)", "data_sensitivity": "Audit Logs & Telemetry", "number_of_users": 35, "location": "AWS Mumbai", "system_availability": "99.95%", "owner": "SOC Team", "status": "Active"},
        {"asset_id": "AST-117", "asset_name": "Corporate VPN Concentrator Gateways", "asset_type": "Network Device", "asset_value": 11000000, "criticality": 4, "business_importance": "High", "internet_exposure": "Yes (Public)", "data_sensitivity": "Session Keys & IPsec", "number_of_users": 4500, "location": "Dual Region (MUM/HYD)", "system_availability": "99.99%", "owner": "Network Engineering", "status": "Active"},
        {"asset_id": "AST-118", "asset_name": "Mobile Banking Android/iOS Backend", "asset_type": "Web Application", "asset_value": 35000000, "criticality": 5, "business_importance": "Mission Critical", "internet_exposure": "Yes (Public Internet)", "data_sensitivity": "Mobile Session Tokens", "number_of_users": 1500000, "location": "AWS ap-south-1", "system_availability": "99.99%", "owner": "Mobile Banking Division", "status": "Active"},
        {"asset_id": "AST-119", "asset_name": "Secure Cloud Storage S3 / Object Vault", "asset_type": "Cloud Resource", "asset_value": 14000000, "criticality": 3, "business_importance": "Moderate", "internet_exposure": "No (Restricted IAM)", "data_sensitivity": "Customer Statements/PDFs", "number_of_users": 1200000, "location": "AWS S3 Mumbai", "system_availability": "99.99%", "owner": "Cloud Infrastructure", "status": "Active"},
        {"asset_id": "AST-120", "asset_name": "Branch Office IoT Surveillance & Biometrics", "asset_type": "IoT Device", "asset_value": 6500000, "criticality": 2, "business_importance": "Physical Security", "internet_exposure": "No (Local VLAN)", "data_sensitivity": "CCTV Footage & Access", "number_of_users": 1200, "location": "450 Bank Branches", "system_availability": "99.0%", "owner": "Physical Security Ops", "status": "Active"}
    ])

def get_initial_vulnerabilities_df() -> pd.DataFrame:
    """Returns 30 enterprise vulnerabilities with CVE, CVSS, and KEV status."""
    return pd.DataFrame([
        {"vulnerability_id": "VULN-001", "cve_id": "CVE-2023-34362", "vulnerability_name": "MOVEit Transfer SQL Injection RCE", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.95, "vulnerability_age_days": 240, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-102", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-002", "cve_id": "CVE-2021-44228", "vulnerability_name": "Apache Log4j2 JNDI Remote Code Execution (Log4Shell)", "cvss_score": 10.0, "severity": "Critical", "exploitability": 1.00, "vulnerability_age_days": 820, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-107", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-003", "cve_id": "CVE-2023-4966", "vulnerability_name": "Citrix Bleed Sensitive Session Token Disclosure", "cvss_score": 9.4, "severity": "Critical", "exploitability": 0.90, "vulnerability_age_days": 130, "patch_status": "In-Progress", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-117", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-004", "cve_id": "CVE-2024-21762", "vulnerability_name": "FortiOS SSL-VPN Out-of-Bounds Write RCE", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.94, "vulnerability_age_days": 50, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-110", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-005", "cve_id": "CVE-2023-23397", "vulnerability_name": "Microsoft Outlook NTLM Net-NTLMv2 Hash Theft", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.88, "vulnerability_age_days": 320, "patch_status": "Patched", "public_exploit": "PoC Available", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-106", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-006", "cve_id": "CVE-2023-22515", "vulnerability_name": "Atlassian Confluence Server Broken Access Control", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.92, "vulnerability_age_days": 160, "patch_status": "In-Progress", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-104", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-007", "cve_id": "CVE-2024-1709", "vulnerability_name": "ConnectWise ScreenConnect Authentication Bypass", "cvss_score": 10.0, "severity": "Critical", "exploitability": 1.00, "vulnerability_age_days": 35, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-106", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-008", "cve_id": "CVE-2023-38545", "vulnerability_name": "cURL SOCKS5 Heap-based Buffer Overflow", "cvss_score": 7.5, "severity": "High", "exploitability": 0.65, "vulnerability_age_days": 190, "patch_status": "Patched", "public_exploit": "PoC Available", "kev_status": "Not Listed", "affected_asset": "AST-105", "attack_vector": "Network", "attack_complexity": "High"},
        {"vulnerability_id": "VULN-009", "cve_id": "CVE-2024-21887", "vulnerability_name": "Ivanti Connect Secure Command Injection RCE", "cvss_score": 9.1, "severity": "Critical", "exploitability": 0.89, "vulnerability_age_days": 75, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-117", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-010", "cve_id": "CVE-2022-22965", "vulnerability_name": "Spring Framework RCE (Spring4Shell)", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.90, "vulnerability_age_days": 700, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-118", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-011", "cve_id": "CVE-2023-2868", "vulnerability_name": "Barracuda Email Security Gateway Command Injection", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.94, "vulnerability_age_days": 270, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-109", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-012", "cve_id": "CVE-2023-46805", "vulnerability_name": "Ivanti EPMM Authentication Bypass", "cvss_score": 8.2, "severity": "High", "exploitability": 0.82, "vulnerability_age_days": 80, "patch_status": "In-Progress", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-117", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-013", "cve_id": "CVE-2023-27997", "vulnerability_name": "Fortinet FortiGate SSL-VPN Heap Buffer Overflow", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.95, "vulnerability_age_days": 260, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-110", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-014", "cve_id": "CVE-2022-26134", "vulnerability_name": "Confluence OGNL Injection Leading to Arbitrary Code", "cvss_score": 7.5, "severity": "High", "exploitability": 0.70, "vulnerability_age_days": 540, "patch_status": "Patched", "public_exploit": "PoC Available", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-104", "attack_vector": "Network", "attack_complexity": "Medium"},
        {"vulnerability_id": "VULN-015", "cve_id": "CVE-2024-20353", "vulnerability_name": "Cisco Adaptive Security Appliance DoS Vulnerability", "cvss_score": 8.6, "severity": "High", "exploitability": 0.80, "vulnerability_age_days": 40, "patch_status": "In-Progress", "public_exploit": "PoC Available", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-110", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-016", "cve_id": "CVE-2023-20198", "vulnerability_name": "Cisco IOS XE Web UI Privilege Escalation", "cvss_score": 10.0, "severity": "Critical", "exploitability": 1.00, "vulnerability_age_days": 140, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-108", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-017", "cve_id": "CVE-2023-36884", "vulnerability_name": "Microsoft Office & Windows HTML RCE Vulnerability", "cvss_score": 8.8, "severity": "High", "exploitability": 0.75, "vulnerability_age_days": 230, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-106", "attack_vector": "Network", "attack_complexity": "Medium"},
        {"vulnerability_id": "VULN-018", "cve_id": "CVE-2024-23897", "vulnerability_name": "Jenkins Core Arbitrary File Read Vulnerability", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.92, "vulnerability_age_days": 60, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-112", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-019", "cve_id": "CVE-2023-38606", "vulnerability_name": "Apple WebKit Zero-Day Memory Corruption (Triangulation)", "cvss_score": 7.8, "severity": "High", "exploitability": 0.72, "vulnerability_age_days": 210, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-106", "attack_vector": "Network", "attack_complexity": "Medium"},
        {"vulnerability_id": "VULN-020", "cve_id": "CVE-2023-48795", "vulnerability_name": "Terrapin Attack: SSH Prefix Truncation Vulnerability", "cvss_score": 5.9, "severity": "Medium", "exploitability": 0.52, "vulnerability_age_days": 90, "patch_status": "In-Progress", "public_exploit": "PoC Available", "kev_status": "Not Listed", "affected_asset": "AST-101", "attack_vector": "Adjacent", "attack_complexity": "High"},
        {"vulnerability_id": "VULN-021", "cve_id": "CVE-2023-32439", "vulnerability_name": "WebKit Type Confusion leading to Arbitrary Code", "cvss_score": 8.8, "severity": "High", "exploitability": 0.78, "vulnerability_age_days": 250, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-118", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-022", "cve_id": "CVE-2024-3094", "vulnerability_name": "XZ Utils Embedded Malicious Backdoor (liblzma)", "cvss_score": 10.0, "severity": "Critical", "exploitability": 1.00, "vulnerability_age_days": 15, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-112", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-023", "cve_id": "CVE-2023-36563", "vulnerability_name": "Microsoft WordPad Information Disclosure Vulnerability", "cvss_score": 6.5, "severity": "Medium", "exploitability": 0.60, "vulnerability_age_days": 150, "patch_status": "Patched", "public_exploit": "PoC Available", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-106", "attack_vector": "Local", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-024", "cve_id": "CVE-2023-42793", "vulnerability_name": "JetBrains TeamCity Authentication Bypass RCE", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.94, "vulnerability_age_days": 170, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-112", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-025", "cve_id": "CVE-2024-21413", "vulnerability_name": "Microsoft Outlook Moniker RCE Vulnerability", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.93, "vulnerability_age_days": 48, "patch_status": "Unpatched", "public_exploit": "PoC Available", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-109", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-026", "cve_id": "CVE-2023-3519", "vulnerability_name": "Citrix ADC & Gateway Remote Code Execution", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.95, "vulnerability_age_days": 230, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-117", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-027", "cve_id": "CVE-2023-29357", "vulnerability_name": "Microsoft SharePoint Server Privilege Escalation", "cvss_score": 8.8, "severity": "High", "exploitability": 0.76, "vulnerability_age_days": 240, "patch_status": "Patched", "public_exploit": "PoC Available", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-113", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-028", "cve_id": "CVE-2024-27198", "vulnerability_name": "JetBrains TeamCity Web Auth Bypass", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.95, "vulnerability_age_days": 25, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-112", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-029", "cve_id": "CVE-2023-20887", "vulnerability_name": "VMware Aria Operations Command Injection RCE", "cvss_score": 9.8, "severity": "Critical", "exploitability": 0.91, "vulnerability_age_days": 280, "patch_status": "Patched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-103", "attack_vector": "Network", "attack_complexity": "Low"},
        {"vulnerability_id": "VULN-030", "cve_id": "CVE-2024-3400", "vulnerability_name": "Palo Alto Networks PAN-OS GlobalProtect Command Injection", "cvss_score": 10.0, "severity": "Critical", "exploitability": 1.00, "vulnerability_age_days": 10, "patch_status": "Unpatched", "public_exploit": "Weaponized", "kev_status": "Known Exploited (CISA)", "affected_asset": "AST-110", "attack_vector": "Network", "attack_complexity": "Low"}
    ])

def get_initial_threats_df() -> pd.DataFrame:
    """Returns 15 realistic cybersecurity threat scenarios and adversary profiles."""
    return pd.DataFrame([
        {"threat_id": "THR-01", "threat_name": "Ransomware & Multi-Stage Extortion", "threat_type": "Ransomware", "severity": "Critical", "frequency": 4.5, "likelihood": 0.82, "attack_vector": "Phishing / Exposed VPN / Lateral Move", "threat_actor": "LockBit 3.0 / BlackCat Gangs", "affected_asset": "AST-101", "historical_attack_count": 16, "exploit_availability": "Weaponized Tools", "threat_intel_score": 95, "status": "Active"},
        {"threat_id": "THR-02", "threat_name": "Executive Spear Phishing & OAuth Consent Abuse", "threat_type": "Phishing", "severity": "High", "frequency": 32.0, "likelihood": 0.94, "attack_vector": "Email / EvilProxy Reverse Proxy", "threat_actor": "Storm-0831 / Initial Access Brokers", "affected_asset": "AST-109", "historical_attack_count": 185, "exploit_availability": "Automated Kits", "threat_intel_score": 90, "status": "Active"},
        {"threat_id": "THR-03", "threat_name": "Volumetric & Layer 7 HTTP/2 Rapid Reset DDoS", "threat_type": "DDoS", "severity": "High", "frequency": 14.0, "likelihood": 0.70, "attack_vector": "HTTP/2 Stream Multiplexing Floods", "threat_actor": "Anonymous Sudan / Killnet", "affected_asset": "AST-102", "historical_attack_count": 64, "exploit_availability": "Botnet SaaS", "threat_intel_score": 78, "status": "Active"},
        {"threat_id": "THR-04", "threat_name": "Infostealer Malware & Session Token Hijacking", "threat_type": "Malware", "severity": "High", "frequency": 22.0, "likelihood": 0.85, "attack_vector": "Trojanized Installer / Malvertising", "threat_actor": "Lumma / RedLine Operators", "affected_asset": "AST-106", "historical_attack_count": 110, "exploit_availability": "Dark Web SaaS", "threat_intel_score": 88, "status": "Active"},
        {"threat_id": "THR-05", "threat_name": "Active Directory Kerberoasting & Golden Ticket", "threat_type": "Credential Theft", "severity": "Critical", "frequency": 6.5, "likelihood": 0.65, "attack_vector": "Internal Recon / Mimikatz / Rubeus", "threat_actor": "APT29 (Cozy Bear) / UNC2452", "affected_asset": "AST-103", "historical_attack_count": 28, "exploit_availability": "Open Source Tooling", "threat_intel_score": 92, "status": "Active"},
        {"threat_id": "THR-06", "threat_name": "Privileged Insider Data Exfiltration", "threat_type": "Insider Threat", "severity": "High", "frequency": 2.5, "likelihood": 0.38, "attack_vector": "Authorized DB Access / USB Dump", "threat_actor": "Disgruntled Employees / Rogue Admin", "affected_asset": "AST-115", "historical_attack_count": 8, "exploit_availability": "Native Admin Tools", "threat_intel_score": 64, "status": "Active"},
        {"threat_id": "THR-07", "threat_name": "OWASP Top 10 API & GraphQL Business Logic Abuse", "threat_type": "Web Attack", "severity": "High", "frequency": 48.0, "likelihood": 0.96, "attack_vector": "BOLA / Mass Assignment / SSRF", "threat_actor": "Opportunistic Scanners & Bug Hunters", "affected_asset": "AST-102", "historical_attack_count": 340, "exploit_availability": "Custom Python Scripts", "threat_intel_score": 89, "status": "Active"},
        {"threat_id": "THR-08", "threat_name": "CI/CD Pipeline Poisoning & Dependency Hijack", "threat_type": "Supply Chain Attack", "severity": "Critical", "frequency": 3.0, "likelihood": 0.52, "attack_vector": "Typosquatting NPM/PyPI / Token Theft", "threat_actor": "Lazarus Group (State-Sponsored)", "affected_asset": "AST-112", "historical_attack_count": 12, "exploit_availability": "Custom Weaponized", "threat_intel_score": 96, "status": "Active"},
        {"threat_id": "THR-09", "threat_name": "UPI & Payment Gateway Fraud Relay", "threat_type": "Financial Fraud", "severity": "Critical", "frequency": 8.0, "likelihood": 0.72, "attack_vector": "MIM / Replay API Attacks / Reverse OTP", "threat_actor": "Organized Financial Crime Syndicates", "affected_asset": "AST-105", "historical_attack_count": 42, "exploit_availability": "Sim-Swap & Botnets", "threat_intel_score": 91, "status": "Active"},
        {"threat_id": "THR-10", "threat_name": "Cloud S3 Bucket Exposure & Misconfiguration", "threat_type": "Cloud Account Hijacking", "severity": "Medium", "frequency": 12.0, "likelihood": 0.45, "attack_vector": "Permissive IAM / Public ACLs", "threat_actor": "Automated Recon Bots", "affected_asset": "AST-119", "historical_attack_count": 55, "exploit_availability": "Automated Shodan/Censys", "threat_intel_score": 70, "status": "Active"},
        {"threat_id": "THR-11", "threat_name": "ATM Network Cash-Out & Malware Injection", "threat_type": "ATM Jackpotting", "severity": "Critical", "frequency": 1.8, "likelihood": 0.30, "attack_vector": "Physical Endoscope / Ploutus Malware", "threat_actor": "Carbanak / FIN7", "affected_asset": "AST-108", "historical_attack_count": 5, "exploit_availability": "Proprietary Malware", "threat_intel_score": 85, "status": "Active"},
        {"threat_id": "THR-12", "threat_name": "SWIFT Alliance Access Wire Tampering", "threat_type": "Interbank Fraud", "severity": "Critical", "frequency": 1.2, "likelihood": 0.22, "attack_vector": "Trojanized PDF / PDF Reader Exploit", "threat_actor": "APT38 (Bluenoroff)", "affected_asset": "AST-111", "historical_attack_count": 3, "exploit_availability": "Advanced Zero-Days", "threat_intel_score": 97, "status": "Active"},
        {"threat_id": "THR-13", "threat_name": "Corporate VPN Credential Stuffing & Spraying", "threat_type": "Credential Theft", "severity": "High", "frequency": 38.0, "likelihood": 0.88, "attack_vector": "Breached Password Combo Lists", "threat_actor": "Automated Botnets", "affected_asset": "AST-117", "historical_attack_count": 210, "exploit_availability": "Open-source SentryMBA", "threat_intel_score": 82, "status": "Active"},
        {"threat_id": "THR-14", "threat_name": "Mobile Banking App Reverse Engineering & Key Extraction", "threat_type": "Mobile Malware", "severity": "High", "frequency": 15.0, "likelihood": 0.68, "attack_vector": "Frida Hooking / Repackaged APKs", "threat_actor": "Godfather / SharkBot Banking Trojans", "affected_asset": "AST-118", "historical_attack_count": 68, "exploit_availability": "Android Malware Kits", "threat_intel_score": 86, "status": "Active"},
        {"threat_id": "THR-15", "threat_name": "Aadhaar / PII Database Scraping via API Abuse", "threat_type": "Data Breach", "severity": "Critical", "frequency": 5.0, "likelihood": 0.60, "attack_vector": "Unauthenticated REST Endpoints", "threat_actor": "Data Brokerage Syndicates", "affected_asset": "AST-115", "historical_attack_count": 19, "exploit_availability": "Fast Scrapers", "threat_intel_score": 90, "status": "Active"}
    ])

def get_initial_controls_df() -> pd.DataFrame:
    """Returns 10 enterprise security controls with costs in INR."""
    return pd.DataFrame([
        {"control_id": "SEC-01", "control_name": "Hardware-Backed Multi-Factor Auth (FIDO2 / MFA)", "category": "Identity & Access", "implementation_cost": 450000, "maintenance_cost": 80000, "effectiveness": 94, "coverage": 88, "risk_reduction_value": 4800000, "detection_capability": 60, "prevention_capability": 96, "status": "Active", "target_threat": "Phishing / Credential Theft"},
        {"control_id": "SEC-02", "control_name": "Next-Gen Web App Firewall & API Protection (WAAP)", "category": "Application Security", "implementation_cost": 750000, "maintenance_cost": 150000, "effectiveness": 89, "coverage": 92, "risk_reduction_value": 6200000, "detection_capability": 88, "prevention_capability": 91, "status": "Active", "target_threat": "Web Application & API Attacks / DDoS"},
        {"control_id": "SEC-03", "control_name": "Endpoint Detection & Response (EDR / XDR)", "category": "Endpoint Security", "implementation_cost": 1100000, "maintenance_cost": 250000, "effectiveness": 92, "coverage": 95, "risk_reduction_value": 8500000, "detection_capability": 96, "prevention_capability": 90, "status": "Active", "target_threat": "Ransomware / Infostealer Malware"},
        {"control_id": "SEC-04", "control_name": "Next-Gen Perimeter Network IDS/IPS with DPI", "category": "Network Security", "implementation_cost": 600000, "maintenance_cost": 120000, "effectiveness": 84, "coverage": 85, "risk_reduction_value": 3900000, "detection_capability": 92, "prevention_capability": 80, "status": "Planned", "target_threat": "Network Intrusion & Exploit Delivery"},
        {"control_id": "SEC-05", "control_name": "24/7 Managed Cloud SIEM & SOC Detection Engine", "category": "Security Operations", "implementation_cost": 1800000, "maintenance_cost": 400000, "effectiveness": 95, "coverage": 95, "risk_reduction_value": 11500000, "detection_capability": 98, "prevention_capability": 72, "status": "Active", "target_threat": "All Complex Threats / APT / Zero-Day"},
        {"control_id": "SEC-06", "control_name": "End-to-End Field-Level AES-256 Encryption & KMS", "category": "Data Protection", "implementation_cost": 650000, "maintenance_cost": 100000, "effectiveness": 96, "coverage": 90, "risk_reduction_value": 7200000, "detection_capability": 45, "prevention_capability": 98, "status": "Active", "target_threat": "Data Exfiltration & Insider Threat"},
        {"control_id": "SEC-07", "control_name": "Air-Gapped Immutable Backups & Automated DR", "category": "Resilience & Recovery", "implementation_cost": 950000, "maintenance_cost": 200000, "effectiveness": 98, "coverage": 95, "risk_reduction_value": 12000000, "detection_capability": 35, "prevention_capability": 99, "status": "Active", "target_threat": "Ransomware & Data Destruction"},
        {"control_id": "SEC-08", "control_name": "Simulated Phishing & Continuous Security Awareness", "category": "Human Layer", "implementation_cost": 250000, "maintenance_cost": 50000, "effectiveness": 76, "coverage": 100, "risk_reduction_value": 2900000, "detection_capability": 68, "prevention_capability": 74, "status": "Active", "target_threat": "Spear Phishing & Social Engineering"},
        {"control_id": "SEC-09", "control_name": "Continuous RBVM Vulnerability & Attack Surface Scanner", "category": "Vulnerability Mgmt", "implementation_cost": 500000, "maintenance_cost": 90000, "effectiveness": 87, "coverage": 95, "risk_reduction_value": 4600000, "detection_capability": 95, "prevention_capability": 68, "status": "Planned", "target_threat": "Unpatched CVEs & Asset Discovery"},
        {"control_id": "SEC-10", "control_name": "Zero Trust Microsegmentation & SDP Architecture", "category": "Zero Trust", "implementation_cost": 1500000, "maintenance_cost": 300000, "effectiveness": 96, "coverage": 80, "risk_reduction_value": 9800000, "detection_capability": 88, "prevention_capability": 97, "status": "Planned", "target_threat": "Lateral Movement & Domain Compromise"}
    ])

def get_initial_incidents_df() -> pd.DataFrame:
    """Returns 20 realistic historical cybersecurity incident records."""
    return pd.DataFrame([
        {"incident_id": "INC-2024-001", "date": "2024-01-14", "incident_type": "Spear Phishing Credential Leak", "affected_asset": "AST-109", "financial_loss": 350000, "downtime_hours": 4, "root_cause": "Session token stolen via EvilProxy reverse proxy", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-002", "date": "2024-02-02", "incident_type": "Layer 7 HTTP Rapid Reset DDoS Flood", "affected_asset": "AST-102", "financial_loss": 850000, "downtime_hours": 3.5, "root_cause": "Unmitigated HTTP/2 stream multiplexing vulnerability", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-003", "date": "2024-02-18", "incident_type": "Attempted Ransomware Infiltration", "affected_asset": "AST-106", "financial_loss": 200000, "downtime_hours": 1.0, "root_cause": "Trojanized utility downloaded by remote employee; blocked by EDR", "severity": "Medium", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-004", "date": "2024-03-05", "incident_type": "SQL Injection Attack on Partner API", "affected_asset": "AST-114", "financial_loss": 1200000, "downtime_hours": 6.0, "root_cause": "Improper sanitization on loan application endpoint", "severity": "Critical", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-005", "date": "2024-03-22", "incident_type": "Rogue Contractor USB Data Copy Attempt", "affected_asset": "AST-113", "financial_loss": 150000, "downtime_hours": 0.0, "root_cause": "DLP agent detected unauthorized mass CSV transfer", "severity": "Medium", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-006", "date": "2024-04-10", "incident_type": "Credential Stuffing on NetBanking Login", "affected_asset": "AST-102", "financial_loss": 600000, "downtime_hours": 2.0, "root_cause": "Bot attack using credential dumps from third-party breach", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-007", "date": "2024-04-29", "incident_type": "GitLab CI/CD Token Leak in Public Gist", "affected_asset": "AST-112", "financial_loss": 450000, "downtime_hours": 2.5, "root_cause": "Hardcoded deployment key committed by junior engineer", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-008", "date": "2024-05-14", "incident_type": "Branch Office Router BGP Route Hijack Attempt", "affected_asset": "AST-110", "financial_loss": 300000, "downtime_hours": 1.5, "root_cause": "Upstream ISP misconfiguration mitigated via RPKI", "severity": "Medium", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-009", "date": "2024-06-01", "incident_type": "ATM Switch Firmware Desync Outage", "affected_asset": "AST-108", "financial_loss": 1800000, "downtime_hours": 8.0, "root_cause": "Corrupted configuration push triggered safety failsafe", "severity": "Critical", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0010", "date": "2024-06-20", "incident_type": "Mobile App API BOLA Flaw Exploration", "affected_asset": "AST-118", "financial_loss": 750000, "downtime_hours": 3.0, "root_cause": "Broken object level auth on account summary endpoint", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0011", "date": "2024-07-04", "incident_type": "Infostealer Infection on Treasury Laptop", "affected_asset": "AST-106", "financial_loss": 900000, "downtime_hours": 5.0, "root_cause": "Lumma stealer executed via personal webmail attachment", "severity": "Critical", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0012", "date": "2024-07-25", "incident_type": "Cloud Storage S3 Permissive ACL Audit Flag", "affected_asset": "AST-119", "financial_loss": 100000, "downtime_hours": 0.5, "root_cause": "Temporary staging bucket created without encryption tag", "severity": "Low", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0013", "date": "2024-08-11", "incident_type": "Active Directory Kerberoast Ticket Request Spike", "affected_asset": "AST-103", "financial_loss": 500000, "downtime_hours": 2.0, "root_cause": "Service account with SPN probed by compromised endpoint", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0014", "date": "2024-08-30", "incident_type": "UPI Gateway Reverse OTP Interception Attempt", "affected_asset": "AST-105", "financial_loss": 1400000, "downtime_hours": 4.0, "root_cause": "Fraudulent callback script detected and blocked by WAAP", "severity": "Critical", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0015", "date": "2024-09-15", "incident_type": "Employee Social Engineering Vishing Incident", "affected_asset": "AST-106", "financial_loss": 250000, "downtime_hours": 1.0, "root_cause": "Fake IT helpdesk caller attempted password reset", "severity": "Medium", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0016", "date": "2024-10-02", "incident_type": "Confluence Zero-Day Exploit Probe", "affected_asset": "AST-104", "financial_loss": 650000, "downtime_hours": 3.0, "root_cause": "CVE-2023-22515 scanner probe isolated by perimeter firewall", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0017", "date": "2024-10-24", "incident_type": "Branch CCTV Camera Mirai Botnet Ping", "affected_asset": "AST-120", "financial_loss": 80000, "downtime_hours": 0.0, "root_cause": "Default password scan blocked at branch firewall boundary", "severity": "Low", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0018", "date": "2024-11-12", "incident_type": "Fortinet VPN Buffer Overflow Probe Spike", "affected_asset": "AST-110", "financial_loss": 400000, "downtime_hours": 1.5, "root_cause": "CVE-2024-21762 exploit attempt deflected by IPS signature", "severity": "High", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0019", "date": "2024-12-05", "incident_type": "HR Payroll Batch Execution Exception Outage", "affected_asset": "AST-113", "financial_loss": 220000, "downtime_hours": 3.5, "root_cause": "Corrupted schema import during quarterly migration", "severity": "Low", "resolution_status": "Closed"},
        {"incident_id": "INC-2024-0020", "date": "2024-12-28", "incident_type": "SWIFT Wire Format Verification Desync", "affected_asset": "AST-111", "financial_loss": 1100000, "downtime_hours": 4.5, "root_cause": "Sanctions screening engine timeout caused transaction buffer delay", "severity": "Critical", "resolution_status": "Closed"}
    ])
